AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ECRRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "marconi-tcc"

  Image1:
    Type: "AWS::ECR::Image"
    Properties:
      RepositoryName: "marconi-tcc"
      ImageUri: "marcony3000/tcc-db"

  Image2:
    Type: "AWS::ECR::Image"
    Properties:
      RepositoryName: "marconi-tcc"
      ImageUri: "marcony3000/tcc-app"

  Image3:
    Type: "AWS::ECR::Image"
    Properties:
      RepositoryName: "marconi-tcc"
      ImageUri: "phpmyadmin/phpmyadmin"